### ISSUE TITLE
Failed to retrieve BigQuery table schema

### ISSUE THREAD

**Issue by peiyun2260** [Canner/WrenAI#436]
**Describe the bug**
I have connected to BigQuery but cannot retrieve BigQuery table scheme

**To Reproduce**
1. Connect to DB.
2. Select the table.
3. Click next button.
4. It showed "Failed to create model(s)".
 
**Expected behavior**
It should have successfully retrieved table schema

**Screenshots**
<img width="1440" alt="image" src="https://github.com/Canner/WrenAI/assets/56057139/3971353b-6893-4758-8143-631ab1239b19">

**Desktop (please complete the following information):**
 - OS: macOS 13.6.7
 - Browser : chrome
 - Chipset : Apple M1

**WrenAI Information**
- Version: wren-ui-0.7.2

Thanks!

**Comment by cyyeh** [comment]
@peiyun2260 can u give us the complete information of the error log in console?

**Comment by peiyun2260** [comment]
Sure here is the complete error log. Please note that I have updated the screenshot above. There is only one error message as shown.

`Uncaught (in promise) ApolloError
    at new ApolloError (_app-233c5554763f2671.js:25:1863)
    at _app-233c5554763f2671.js:6:245021
    at both (_app-233c5554763f2671.js:6:213409)
    at _app-233c5554763f2671.js:6:213310
    at new Promise (<anonymous>)
    at Object.then (_app-233c5554763f2671.js:6:213277)
    at Object.next (_app-233c5554763f2671.js:6:213419)
    at notifySubscription (_app-233c5554763f2671.js:6:166845)
    at onNotify (_app-233c5554763f2671.js:6:167480)
    at a.next (_app-233c5554763f2671.js:6:168128)
ApolloError @ _app-233c5554763f2671.js:25
(anonymous) @ _app-233c5554763f2671.js:6
both @ _app-233c5554763f2671.js:6
(anonymous) @ _app-233c5554763f2671.js:6
then @ _app-233c5554763f2671.js:6
(anonymous) @ _app-233c5554763f2671.js:6
notifySubscription @ _app-233c5554763f2671.js:6
onNotify @ _app-233c5554763f2671.js:6
a.next @ _app-233c5554763f2671.js:6
(anonymous) @ _app-233c5554763f2671.js:6
iterateObserversSafely @ _app-233c5554763f2671.js:6
next @ _app-233c5554763f2671.js:6
notifySubscription @ _app-233c5554763f2671.js:6
onNotify @ _app-233c5554763f2671.js:6
a.next @ _app-233c5554763f2671.js:6
next @ _app-233c5554763f2671.js:6
notifySubscription @ _app-233c5554763f2671.js:6
onNotify @ _app-233c5554763f2671.js:6
a.next @ _app-233c5554763f2671.js:6
await in a.next (async)
onNext @ models-0b5f8697a4a8011e.js:1
(anonymous) @ 261-4dcf980cdebcd9a8.js:1
Promise.then (async)
onClick @ 261-4dcf980cdebcd9a8.js:1
handleClick @ 566-b87dcf1b7c3c6672.js:1
Nb @ framework-467b11a89995b152.js:9
Tb @ framework-467b11a89995b152.js:9
(anonymous) @ framework-467b11a89995b152.js:9
nf @ framework-467b11a89995b152.js:9
se @ framework-467b11a89995b152.js:9
(anonymous) @ framework-467b11a89995b152.js:9
Rk @ framework-467b11a89995b152.js:9
Jb @ framework-467b11a89995b152.js:9
hd @ framework-467b11a89995b152.js:9
fd @ framework-467b11a89995b152.js:9
ed @ framework-467b11a89995b152.js:9Understand this error`
