### ISSUE TITLE
Error when start wren-ai-service

### ISSUE THREAD

**Issue by jcnapoles** [Canner/WrenAI#444]
**Describe the bug**
When start wren-ai-service fail with an error. See attached screenshot

**To Reproduce**
1-Go to docker folder
2- Config env files
3-Execute docker-compose --env-file .env.local up -d

**Expected behavior**
Expected that eradicate this error and works as usually

**Screenshots**

![image](https://github.com/Canner/WrenAI/assets/41384050/807fae01-e0cf-4176-8528-f352a57012ac)

**Container Logs **
You can execute the following command to get the logs of containers and provide them here:
ERROR:    Application startup failed. Exiting.
2024-06-26 15:31:49 INFO:     Started server process [7]
2024-06-26 15:31:49 INFO:     Waiting for application startup.
2024-06-26 15:31:49 2024-06-26 13:31:49,380 - wren-ai-service - INFO - Initializing providers... (utils.py:63)
2024-06-26 15:31:50 ERROR:    Traceback (most recent call last):
2024-06-26 15:31:50   File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in lifespan
2024-06-26 15:31:50     async with self.lifespan_context(app) as maybe_state:
2024-06-26 15:31:50   File "/usr/local/lib/python3.12/contextlib.py", line 204, in __aenter__
2024-06-26 15:31:50     return await anext(self.gen)
2024-06-26 15:31:50            ^^^^^^^^^^^^^^^^^^^^^
2024-06-26 15:31:50   File "/src/__main__.py", line 28, in lifespan
2024-06-26 15:31:50     container.init_globals()
2024-06-26 15:31:50   File "/src/globals.py", line 39, in init_globals
2024-06-26 15:31:50     llm_provider, document_store_provider, engine = init_providers()
2024-06-26 15:31:50                                                     ^^^^^^^^^^^^^^^^
2024-06-26 15:31:50   File "/src/utils.py", line 64, in init_providers
2024-06-26 15:31:50     loader.import_mods()
2024-06-26 15:31:50   File "/src/providers/loader.py", line 39, in import_mods
2024-06-26 15:31:50     importlib.import_module(name)
2024-06-26 15:31:50   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-06-26 15:31:50     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-26 15:31:50            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
2024-06-26 15:31:50   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-06-26 15:31:50   File "/src/providers/document_store/qdrant.py", line 195, in <module>
2024-06-26 15:31:50     class QdrantProvider(DocumentStoreProvider):
2024-06-26 15:31:50   File "/src/providers/document_store/qdrant.py", line 206, in QdrantProvider
2024-06-26 15:31:50     or get_default_embedding_model_dim(os.getenv("LLM_PROVIDER", "opeani")),
2024-06-26 15:31:50        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26 15:31:50   File "/src/providers/loader.py", line 97, in get_default_embedding_model_dim
2024-06-26 15:31:50     return importlib.import_module(
2024-06-26 15:31:50            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26 15:31:50   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-06-26 15:31:50     return _bootstrap._gcd_import(name[level:], package, level)
2024-06-26 15:31:50            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
2024-06-26 15:31:50   File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
2024-06-26 15:31:50 ModuleNotFoundError: No module named 'src.providers.llm.opeani'
2024-06-26 15:31:50 
2024-06-26 15:31:50 ERROR:    Application startup failed. Exiting.

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [brave]

**Wren AI Information**
- Version: [wren-ai-service-0.6.0]

**Additional context**

**Comment by cyyeh** [comment]
@jcnapoles thanks for catching the typo! We'll fix this as soon as possible

**Comment by cyyeh** [comment]
@jcnapoles We've released a new version of ai service now. Please pull the main branch, thank u

**Comment by jcnapoles** [comment]
Have been fixed the typo.
