### ISSUE TITLE
wren-ai-service is not starting on windows laptop

### ISSUE THREAD

**Issue by KrishnaK-stack** [Canner/WrenAI#569]
**Describe the bug**
wren-ai-service is not starting on windows laptop

**To Reproduce**
1. Go to: (https://docs.getwren.ai/installation)
2. Download the exe setup for windows installation

**Expected behavior**
AI service should get started successfully.

**Screenshots**
pls refer error log.

**Desktop (please complete the following information):**
- OS: Windows
- Browser :chrome

**Wren AI Information**
- Version: 0.7.1
- LLM_PROVIDER= openai_llm
- GENERATION_MODEL=  gpt-3.5-turbo

**Additional context**
**Error log :**

INFO: Started server process [7]

INFO: Waiting for application startup.

2024-07-31 06:32:00,422 - wren-ai-service - INFO - Initializing providers... (utils.py:64)

2024-07-31 06:32:01,841 - wren-ai-service - INFO - Registering provider: openai_embedder (loader.py:64)

2024-07-31 06:32:01,841 - wren-ai-service - INFO - Registering provider: qdrant (loader.py:64)

2024-07-31 06:32:01,842 - wren-ai-service - INFO - Registering provider: azure_openai_embedder (loader.py:64)

2024-07-31 06:32:01,843 - wren-ai-service - INFO - Registering provider: ollama_embedder (loader.py:64)

2024-07-31 06:32:01,844 - wren-ai-service - INFO - Registering provider: wren_ui (loader.py:64)

2024-07-31 06:32:01,844 - wren-ai-service - INFO - Registering provider: wren_ibis (loader.py:64)

2024-07-31 06:32:01,847 - wren-ai-service - INFO - Registering provider: azure_openai_llm (loader.py:64)

2024-07-31 06:32:01,849 - wren-ai-service - INFO - Registering provider: ollama_llm (loader.py:64)

2024-07-31 06:32:01,850 - wren-ai-service - INFO - Registering provider: openai_llm (loader.py:64)

2024-07-31 06:32:01,850 - wren-ai-service - INFO - Using OpenAILLM provider with API base: https://api.openai.com/v1 (openai.py:135)

ERROR: Traceback (most recent call last):

File "/app/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions

yield

File "/app/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 233, in handle_request

resp = self._pool.handle_request(req)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request

raise exc from None

File "/app/.venv/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request

response = connection.handle_request(

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 99, in handle_request

raise exc

File "/app/.venv/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 76, in handle_request

stream = self._connect(request)

^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 154, in _connect

stream = stream.start_tls(**kwargs)

^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpcore/_backends/sync.py", line 152, in start_tls

with map_exceptions(exc_map):

File "/usr/local/lib/python3.12/contextlib.py", line 155, in __exit__

self.gen.throw(value)

File "/app/.venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions

raise to_exc(exc) from exc

httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 952, in _request

response = self._client.send(

^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpx/_client.py", line 914, in send

response = self._send_handling_auth(

^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpx/_client.py", line 942, in _send_handling_auth

response = self._send_handling_redirects(

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpx/_client.py", line 979, in _send_handling_redirects

response = self._send_single_request(request)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1015, in _send_single_request

response = transport.handle_request(request)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 232, in handle_request

with map_httpcore_exceptions():

File "/usr/local/lib/python3.12/contextlib.py", line 155, in __exit__

self.gen.throw(value)

File "/app/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions

raise mapped_exc(message) from exc

httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 734, in lifespan

async with self.lifespan_context(app) as maybe_state:

File "/usr/local/lib/python3.12/contextlib.py", line 204, in __aenter__

return await anext(self.gen)

^^^^^^^^^^^^^^^^^^^^^

File "/src/__main__.py", line 28, in lifespan

container.init_globals()

File "/src/globals.py", line 36, in init_globals

llm_provider, embedder_provider, document_store_provider, engine = init_providers()

^^^^^^^^^^^^^^^^

File "/src/utils.py", line 67, in init_providers

llm_provider = loader.get_provider(os.getenv("LLM_PROVIDER", "openai_llm"))()

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/src/providers/llm/openai.py", line 138, in __init__

_verify_api_key(self._api_key.resolve_value(), self._api_base)

File "/src/providers/llm/openai.py", line 129, in _verify_api_key

OpenAI(api_key=api_key, base_url=api_base).models.list()

File "/app/.venv/lib/python3.12/site-packages/openai/resources/models.py", line 80, in list

return self._get_api_list(

^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1289, in get_api_list

return self._request_api_list(model, page, opts)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1134, in _request_api_list

return self.request(page, options, stream=False)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 921, in request

return self._request(

^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 976, in _request

return self._retry_request(

^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1053, in _retry_request

return self._request(

^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 976, in _request

return self._retry_request(

^^^^^^^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1053, in _retry_request

return self._request(

^^^^^^^^^^^^^^

File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 986, in _request

raise APIConnectionError(request=request) from err

openai.APIConnectionError: Connection error.

ERROR: Application startup failed. Exiting.

**Comment by cyyeh** [comment]
@KrishnaK-stack hi, would you like to try the latest version, which is 0.7.4?

https://github.com/Canner/WrenAI/releases/tag/0.7.4

**Comment by cyyeh** [comment]
issue fixed
