### ISSUE TITLE
wren-ai-service - ERROR - ask pipeline - OTHERS: 'results' (ask.py:322)

### ISSUE THREAD

**Issue by zehuiHuang** [Canner/WrenAI#866]
**Describe the bug**
When I switched to the gemma2:9b  model of Ollama, there was an exception, but both OpenAI and Azure OpenAI were normal

**To Reproduce**
1. use Ollama
2. change gemma2:9b model

**Expected behavior**
query task
<img width="918" alt="image" src="https://github.com/user-attachments/assets/2bf6795f-38b9-49ae-8eaf-672abe51040d">

**Screenshots**
`> construct_retrieval_results [src.pipelines.retrieval.retrieval.construct_retrieval_results()] encountered an error<
> Node inputs:
{'construct_db_schemas': "<Task finished name='Task-207' "
                         'coro=<AsyncGraphAda...',
 'dbschema_retrieval': "<Task finished name='Task-206' coro=<AsyncGraphAda...",
 'filter_columns_in_tables': "<Task finished name='Task-209' "
                             'coro=<AsyncGraphAda...'}
********************************************************************************
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 122, in new_fn
    await fn(**fn_kwargs) if asyncio.iscoroutinefunction(fn) else fn(**fn_kwargs)
                                                                  ^^^^^^^^^^^^^^^
  File "/src/utils.py", line 71, in wrapper_timer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 225, in sync_wrapper
    self._handle_exception(observation, e)
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 428, in _handle_exception
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 223, in sync_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/src/pipelines/retrieval/retrieval.py", line 264, in construct_retrieval_results
    columns_and_tables_needed = orjson.loads(filter_columns_in_tables["replies"][0])[
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'results'
-------------------------------------------------------------------
Oh no an error! Need help with Hamilton?
Join our slack and ask for help! https://join.slack.com/t/hamilton-opensource/shared_invite/zt-1bjs72asx-wcUTgH7q7QX1igiQ5bbdcg
-------------------------------------------------------------------

2024-11-04 08:15:25,189 - wren-ai-service - ERROR - ask pipeline - OTHERS: 'results' (ask.py:322)
Traceback (most recent call last):
  File "/src/web/v1/services/ask.py", line 177, in ask
    retrieval_result = await self._pipelines["retrieval"].run(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/utils.py", line 95, in wrapper_timer
    return await process(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/utils.py", line 79, in process
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 188, in async_wrapper
    self._handle_exception(observation, e)
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 428, in _handle_exception
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 186, in async_wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/pipelines/retrieval/retrieval.py", line 389, in run
    return await self._pipe.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 368, in execute
    raise e
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 359, in execute
    outputs = await self.raw_execute(final_vars, overrides, display_graph, inputs=inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 320, in raw_execute
    raise e
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 315, in raw_execute
    results = await await_dict_of_tasks(task_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 23, in await_dict_of_tasks
    coroutines_gathered = await asyncio.gather(*coroutines)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 36, in process_value
    return await val
           ^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/hamilton/async_driver.py", line 122, in new_fn
    await fn(**fn_kwargs) if asyncio.iscoroutinefunction(fn) else fn(**fn_kwargs)
                                                                  ^^^^^^^^^^^^^^^
  File "/src/utils.py", line 71, in wrapper_timer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 225, in sync_wrapper
    self._handle_exception(observation, e)
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 428, in _handle_exception
    raise e
  File "/app/.venv/lib/python3.12/site-packages/langfuse/decorators/langfuse_decorator.py", line 223, in sync_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/src/pipelines/retrieval/retrieval.py", line 264, in construct_retrieval_results
    columns_and_tables_needed = orjson.loads(filter_columns_in_tables["replies"][0])[
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'results'`

**Desktop (please complete the following information):**

**Wren AI Information**
- Version: [e.g, 0.1.0]
- LLM_PROVIDER= # openai_llm, azure_openai_llm, ollama_llm
- GENERATION_MODEL= # gpt-3.5-turbo, llama3:70b, etc.

**Additional context**

**Comment by devneri** [comment]
Same error. How did you fix it?

**Comment by jeddenkah** [comment]
Me also. But i use llama3.2:1b with ollama. How did you fix it?

**Comment by wwwy3y3** [comment]
@devneri , @jeddenkah feel free to raise your questions on Discord #wren-ai-service channel.

**Comment by Tobewont** [comment]
Same error. When use ollama

**Comment by kubox161** [comment]
Same error. How did you fix it?
